clusters:
- name: alpha
  destinationServer: https://172.26.253.108:6443
  apps:
    sampleApp:
      enabled: true
      branch: HEAD
    prometheus:
      enabled: false

- name: beta
  destinationServer: https://172.26.253.111:6443
  apps:
    sampleApp:
      enabled: true
      branch: HEAD
    prometheus:
      enabled: false
